[workspace]
resolver = "2"
members = [
    "jellyfin-rpc",
    "jellyfin-rpc-cli", "jftest",
]

default-members = [
    "jellyfin-rpc",
    "jellyfin-rpc-cli",
]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
