[package]
name = "jellyfin-rpc"
version = "0.1.0"
edition = "2021"
description  = "Backend for the Jellyfin-RPC-cli and Jellyfin-RPC-Iced projects"
license-file = "LICENSE"
repository   = "https://github.com/Radiicall/jellyfin-rpc"

[features]
imgur = []
cli = ["dep:colored"]

[dependencies]
discord-rich-presence = "0.2"
retry                 = "2.0"
serde_json            = "1.0"


[dependencies.colored]
version = "2.0"
optional = true

[dependencies.serde]
features = ["derive"]
version  = "1.0"

[dependencies.reqwest]
default-features = false
features = ["rustls-tls", "json"]
version  = "0.11"
